@host = http://localhost:65044

###

# @name login
POST {{host}}/Account/Login
Content-Type: application/json

{
    "username": "User3",
    "password": "Password3"
}

###

# @name logout
GET {{host}}/Account/Logout

###

# @name NoAttribute
GET {{host}}/Sample/NoAttribute

###

# @name AllowAnonymous
GET {{host}}/Sample/AllowAnonymous

###

# @name Content
GET {{host}}/Sample/Content

###

# @name Authorize
GET {{host}}/Sample/Authorize

###